TWITTER_KEY: 'hogehoge'
TWITTER_SECRET: 'fugofugo'
TWITTER_OAUTH_TOKEN: '@ktra_appのOAUTH token入れてください'
TWITTER_OAUTH_SECRET: '@ktra_appのOAUTH secret入れてください'
TWITTER_TRACK_KEYWORDS: '@ktra_app'
production:
  BUGSNAG_API_KEY: ''
  SECRET_TOKEN: 'aaa'
  SESSION_KEY: '_ktra_session'
staging:
  RAILS_ENV: 'staging'
  RACK_ENV: 'staging'
  SECRET_TOKEN: 'bbb'
