TWITTER_KEY: 'hogehoge'
TWITTER_SECRET: 'fugofugo'
production:
  BUGSNAG_API_KEY: ''
  SECRET_TOKEN: 'aaa'
  SESSION_KEY: '_ktra_session'
staging:
  RAILS_ENV: 'staging'
  RACK_ENV: 'staging'
  SECRET_TOKEN: 'bbb'
