development: &development
  adapter: postgresql
  database: ktra_development
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

test:
  <<: *development
  database: ktra_test

staging:
  <<: *development
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *development
  url: <%= ENV["DATABASE_URL"] %>
